version: '2.1'

services:
  redis:
    image: redis
    ports:
      - 6379:6379

  web:
    image: workshop:latest
    build: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=
    ports:
      - 9000:9000
    depends_on:
      - redis
    links:
      - redis
